#!/bin/bash


mejor_de_5() {


    local i

    player_points=0
    rival_points=0

    for ((i = 1; i <= 5; i++)); do

        echo
        echo "RONDA $i"
        echo "Elige"
        echo "1 --> Piedra"
        echo "2 --> Papel"
        echo "3 --> Tijeras"

        echo -n "Seleccionas: "
        read -r elec

        while [[ $elec -gt 3 ]]; do

            echo
            echo "Elección no valida, vuelve a elegir"

            echo "1 --> Piedra"
            echo "2 --> Papel"
            echo "3 --> Tijeras"

            echo -n "Seleccionas: "
            read -r elec
        
        done

        # Damos por hecho de que el usuario ha escogido ya sea 1, 2 o 3

        case $elec in
            1) player="piedra" ;; # si $elec=1) comandos...
            2) player="papel" ;; # si $elec=2) comandos...
            3) player="tijeras" ;; # si $elec=3) comandos...
        esac

        echo "Has seleccionado: $player"

        num_random=$((RANDOM%3 + 1))

        case $num_random in
            1) rival="piedra" ;; # si $elec=1) comandos...
            2) rival="papel" ;; # si $elec=2) comandos...
            3) rival="tijeras" ;; # si $elec=3) comandos...
        esac

        echo "Tu rival a seleccionado: $rival"

         # GANAS

        # Piedra(1) gana a tijeras(3)
        # Papel(2) gana a piedra(1)
        # Tijeras(3) gana a papel(2)

        # PIERDES 

        # Tijeras(3) pierde contra piedra(1)
        # Piedra(1) pierde contra Papel(2)
        # Papel(2) pierde contra tijeras(3)

        # elec = num_random --> EMPATE

        if [[ $elec -eq $num_random ]]; then

            echo "EMPATE"
            echo "Tú: $player_points Rival: $rival_points"

        else 

            case "$elec-$num_random" in

                1-3) 
                    echo "GANAS TÚ (Piedra gana a tijeras)"
                    ((player_points++))
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
                2-1) 
                    echo "GANAS TÚ (Papel gana a piedra)"
                    ((player_points++))
                    echo "Tú: $player_points Rival: $rival_points"  
                    ;;
                3-2) 
                    echo "GANAS TÚ (Tijeras gana a papel)"
                    ((player_points++)) 
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
                3-1) 
                    echo "PIERDES (Tijeras pierde contra piedra)"
                    ((rival_points++))
                    echo "Tú: $player_points Rival: $rival_points"    
                    ;;
                1-2) 
                    echo "PIERDES (Piedra pierde contra papel)" 
                    ((rival_points++))
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
                2-3) 
                    echo "PIERDES (Papel pierde contra tijeras)" 
                    ((rival_points++))
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;

            esac

        fi

    #sleep 3

    #clear
        

    done

    if [[ $player_points -gt $rival_points ]]; then

        echo
        echo "Has ganado ($player_points-$rival_points)"
        echo

    else

        echo 
        echo "Has perdido ($player_points-$rival_points)"
        echo

    fi

    


}

infinito() {

    player_points=0
    rival_points=0

    local i=1

    while true; do

        


        echo
        echo "RONDA $i"
        echo "Elige"
        echo "1 --> Piedra"
        echo "2 --> Papel"
        echo "3 --> Tijeras"

        echo -n "Seleccionas: "
        read -r elec

        while [[ $elec -gt 3 ]]; do

            echo
            echo "Elección no valida, vuelve a elegir"

            echo "1 --> Piedra"
            echo "2 --> Papel"
            echo "3 --> Tijeras"

            echo -n "Seleccionas: "
            read -r elec
            
        done

        # Damos por hecho de que el usuario ha escogido ya sea 1, 2 o 3

        case $elec in
            1) player="piedra" ;; # si $elec=1) comandos...
            2) player="papel" ;; # si $elec=2) comandos...
            3) player="tijeras" ;; # si $elec=3) comandos...
        esac

        echo "Has seleccionado: $player"

        num_random=$((RANDOM%3 + 1))

        case $num_random in
            1) rival="piedra" ;; # si $elec=1) comandos...
            2) rival="papel" ;; # si $elec=2) comandos...
            3) rival="tijeras" ;; # si $elec=3) comandos...
        esac

        echo "Tu rival a seleccionado: $rival"

        # GANAS

        # Piedra(1) gana a tijeras(3)
        # Papel(2) gana a piedra(1)
        # Tijeras(3) gana a papel(2)

        # PIERDES 

        # Tijeras(3) pierde contra piedra(1)
        # Piedra(1) pierde contra Papel(2)
        # Papel(2) pierde contra tijeras(3)

        # elec = num_random --> EMPATE

        if [[ $elec -eq $num_random ]]; then

            echo "EMPATE"
            echo "Tú: $player_points Rival: $rival_points"

        else 

            case "$elec-$num_random" in
                1-3) 
                    echo "GANAS TÚ (Piedra gana a tijeras)"
                    ((player_points++))
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
                2-1) 
                    echo "GANAS TÚ (Papel gana a piedra)"
                    ((player_points++))
                    echo "Tú: $player_points Rival: $rival_points"  
                    ;;
                3-2) 
                    echo "GANAS TÚ (Tijeras gana a papel)"
                    ((player_points++)) 
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
                3-1) 
                    echo "PIERDES (Tijeras pierde contra piedra)"
                    ((rival_points++))
                    echo "Tú: $player_points Rival: $rival_points"    
                    ;;
                1-2) 
                    echo "PIERDES (Piedra pierde contra papel)" 
                    ((rival_points++))
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
                2-3) 
                    echo "PIERDES (Papel pierde contra tijeras)" 
                    ((rival_points++))
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
            esac

            ((i++))

        fi

    done

    
}

imposible() {

    player_points=0
    rival_points=0

    local i=1

    while true; do


        echo
        echo "RONDA $i"
        echo "Elige"
        echo "1 --> Piedra"
        echo "2 --> Papel"
        echo "3 --> Tijeras"

        echo -n "Seleccionas: "
        read -r elec

        while [[ $elec -gt 3 ]]; do

            echo
            echo "Elección no valida, vuelve a elegir"

            echo "1 --> Piedra"
            echo "2 --> Papel"
            echo "3 --> Tijeras"

            echo -n "Seleccionas: "
            read -r elec
            
        done

        # Damos por hecho de que el usuario ha escogido ya sea 1, 2 o 3

        case $elec in
            1) player="piedra" ;; # si $elec=1) comandos...
            2) player="papel" ;; # si $elec=2) comandos...
            3) player="tijeras" ;; # si $elec=3) comandos...
        esac

        echo "Has seleccionado: $player"

        #num_random=$((RANDOM%3 + 1))

        case $elec in
            1) num_rival=2 ;; #elec(1:piedra)-num_rival(2:papel)
            2) num_rival=3 ;; #elec(2:papel)-num_rival(3:tijeras)
            3) num_rival=1  ;; #elec(3:tijeras)-num_rival(1:piedra)
        esac

        case $num_rival in
            1) rival="piedra" ;; # si $elec=1) comandos...
            2) rival="papel" ;; # si $elec=2) comandos...
            3) rival="tijeras" ;; # si $elec=3) comandos...
        esac

        echo "Tu rival a seleccionado: $rival"

        # GANAS

        # Piedra(1) gana a tijeras(3)
        # Papel(2) gana a piedra(1)
        # Tijeras(3) gana a papel(2)

        # PIERDES 

        # Tijeras(3) pierde contra piedra(1)
        # Piedra(1) pierde contra Papel(2)
        # Papel(2) pierde contra tijeras(3)

        # elec = num_random --> EMPATE

        if [[ $elec -eq $num_rival ]]; then

            echo "EMPATE"
            echo "Tú: $player_points Rival: $rival_points"

        else 

            case "$elec-$num_rival" in
                1-3) 
                    echo "GANAS TÚ (Piedra gana a tijeras)"
                    ((player_points++))
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
                2-1) 
                    echo "GANAS TÚ (Papel gana a piedra)"
                    ((player_points++))
                    echo "Tú: $player_points Rival: $rival_points"  
                    ;;
                3-2) 
                    echo "GANAS TÚ (Tijeras gana a papel)"
                    ((player_points++)) 
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
                3-1) 
                    echo "PIERDES (Tijeras pierde contra piedra)"
                    ((rival_points++))
                    echo "Tú: $player_points Rival: $rival_points"    
                    ;;
                1-2) 
                    echo "PIERDES (Piedra pierde contra papel)" 
                    ((rival_points++))
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
                2-3) 
                    echo "PIERDES (Papel pierde contra tijeras)" 
                    ((rival_points++))
                    echo "Tú: $player_points Rival: $rival_points"   
                    ;;
            esac

            ((i++))

        fi

    done

}




echo
echo "Este es un juego de piedra, papel y tijeras"
echo
echo "Hay tres modos:"
echo "1 --> Mejor de 5"
echo "2 --> Infinito"
echo "3 --> Imposible"
echo
echo -n "Seleccionas: "
read -r modo

if [[ $modo -eq 1 ]]; then

    echo "Has elegido jugar al modo mejor de 5"
    mejor_de_5

elif [[ $modo -eq 2 ]]; then
    
    echo "Has elegido jugar al modo infinito"
    infinito

elif [[ $modo -eq 3 ]]; then

    echo "Has elegido jugar al modo imposible"
    imposible

else 

    echo "Elección no valida"

fi